version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: desafio_service
      POSTGRES_PASSWORD: desafio_service
      POSTGRES_DB: desafio_service
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U desafio_service"]
      interval: 2s
      timeout: 3s
      retries: 30